%% Get the FBG needle information
fbgneedle_param_file = fullfile( ...
    "~/dev/git/amiro/data", ...
    "7CH-4AA-0001-MCF-even", ...
    "7CH-4AA-0001-MCF-even_needle_params_2023-03-29_Jig-Calibration_best.json" ...
);

fbgneedle = FBGNeedle.load_json(fbgneedle_param_file);


%% Get the Directory information
data_dir = fullfile( ...
    "~/data/", ...
    fbgneedle.serial_number, ...
    "2023-06-15_2023-06-16_Beef-Insertion-Experiment",...
    "processed_bags",...
    "2023-06-15"...
);

insertion_dirs = dir(data_dir);
insertion_dirs = insertion_dirs( ...
    [insertion_dirs.isdir] ...
    & contains({insertion_dirs.name}, "Insertion") ...
);

sensor_data_filename         = "fbg_sensor_data.xlsx";
updated_sensor_data_filename = strrep(sensor_data_filename, ".xlsx", "_matlab-post-proc.xlsx");

%% Run through the experiments
for expmt_i = 1:numel(insertion_dirs)
    insertion_dir = insertion_dirs(expmt_i);
    
    sensor_data_files = dir( ...
        fullfile( ...
            insertion_dir.folder, ...
            insertion_dir.name, ...
            "*", ...
            sensor_data_filename ...
        )...
    );
    
    %% Run through each of the sensors
    for data_i = 1:numel(sensor_data_files)
        sensor_data_file = sensor_data_files(data_i);
        
        % load the wavelength shifts
        wl_shifts = readtable( ...
            fullfile( sensor_data_file.folder, sensor_data_file.name ), ...
            "Sheet", "processed wavelengths", ...
            "VariableNamingRule","modify" ...
        );
        wl_shifts.Properties.VariableNames(2:end) = fbgneedle.generate_chaa();
        
        % perform temperature compensation
        wl_shifts_tcomp = wl_shifts;
        wl_shifts_tcomp{:, fbgneedle.generate_chaa()} = fbgneedle.temperature_compensate(...
            wl_shifts(:, fbgneedle.generate_chaa())...
        );

        % compute the mean temperature-compensated wavelength shifts
        mean_wl_shifts_tcomp = mean(wl_shifts_tcomp(:, fbgneedle.generate_chaa()), 1);
        
        % save the results
        out_sensor_data_file = fullfile(sensor_data_file.folder, updated_sensor_data_filename);
        writetable( ...
            wl_shifts_tcomp,...
            out_sensor_data_file,...
            'Sheet', 'TComp proc. wavelengths'...
        )

        writetable( ...
            mean_wl_shifts_tcomp, ...
            out_sensor_data_file,...
            'Sheet', 'mean Tcomp proc. wavelengths'...
        )

        fprintf("Saved updated sensor data to: %s\n", out_sensor_data_file);

    end    

end